import type { Product, Category, Industry, AnalyticsData, SalesTrend, Order, Customer, Review, BlogPost, Resource, NavigationItem } from './types';

export const navigation: NavigationItem[] = [
  { id: '1', label: 'Home', url: '/' },
  { id: '2', label: 'Store', url: '/store' },
  { id: '3', label: 'About', url: '/about' },
  { id: '4', label: 'Resources', url: '/resources' },
  { id: '5', label: 'Contact', url: '/contact' },
];

export const categories: Category[] = [
  { _id: 'cat1', name: 'Financial Models', slug: 'financial-models', description: 'Professional financial modeling templates', icon: 'BarChart3', productCount: 12, image: '/images/financial.jpg' },
  { _id: 'cat2', name: 'Dashboards', slug: 'dashboards', description: 'Interactive KPI dashboards', icon: 'LayoutDashboard', productCount: 18, image: '/images/dashboards.jpg' },
  { _id: 'cat3', name: 'Budget Templates', slug: 'budget-templates', description: 'Budget planning and tracking', icon: 'Wallet', productCount: 8, image: '/images/budget.jpg' },
  { _id: 'cat4', name: 'HR Systems', slug: 'hr-systems', description: 'Human resource management systems', icon: 'Users', productCount: 6, image: '/images/hr.jpg' },
  { _id: 'cat5', name: 'Project Management', slug: 'project-management', description: 'Project planning and tracking tools', icon: 'ClipboardCheck', productCount: 7, image: '/images/project.jpg' },
  { _id: 'cat6', name: 'Business Plans', slug: 'business-plans', description: 'Business planning templates', icon: 'FileText', productCount: 5, image: '/images/business-plan.jpg' },
  { _id: 'cat7', name: 'Inventory Systems', slug: 'inventory-systems', description: 'Inventory management solutions', icon: 'Package', productCount: 4, image: '/images/inventory.jpg' },
  { _id: 'cat8', name: 'Bundles', slug: 'bundles', description: 'Discounted product bundles', icon: 'Gift', productCount: 6, image: '/images/bundles.jpg' },
];

export const industries: Industry[] = [
  { id: 'ind1', name: 'Healthcare', slug: 'healthcare', icon: 'HeartPulse', description: 'Hospital & clinic management templates', productCount: 8 },
  { id: 'ind2', name: 'Business', slug: 'business', icon: 'Building2', description: 'Corporate business systems', productCount: 24 },
  { id: 'ind3', name: 'Finance', slug: 'finance', icon: 'TrendingUp', description: 'Financial analysis & planning tools', productCount: 15 },
  { id: 'ind4', name: 'NGO', slug: 'ngo', icon: 'HandHeart', description: 'Non-profit management systems', productCount: 7 },
  { id: 'ind5', name: 'HR', slug: 'hr', icon: 'UserCheck', description: 'Human resource management', productCount: 6 },
  { id: 'ind6', name: 'Schools', slug: 'schools', icon: 'GraduationCap', description: 'Educational institution systems', productCount: 5 },
  { id: 'ind7', name: 'Churches', slug: 'churches', icon: 'Church', description: 'Church administration templates', productCount: 4 },
  { id: 'ind8', name: 'Agriculture', slug: 'agriculture', icon: 'Sprout', description: 'Farm & agribusiness templates', productCount: 3 },
];

export const products: Product[] = [
  {
    _id: 'prod1',
    name: 'Hospital KPI Dashboard Pro',
    sku: 'TW-HKD-001',
    slug: 'hospital-kpi-dashboard-pro',
    shortDescription: 'Comprehensive hospital performance dashboard with 45+ KPI metrics, real-time bed occupancy tracking, and financial reporting.',
    description: 'A complete hospital performance management system designed for Ugandan and East African healthcare facilities. Track patient admissions, bed occupancy, revenue per bed, staff productivity, and clinical outcomes. Includes automated reporting, drill-down capabilities, and mobile-responsive viewing.',
    price: 150000,
    salePrice: 99000,
    category: 'Dashboards',
    industry: 'Healthcare',
    fileType: 'Excel (.xlsx)',
    tags: ['hospital', 'kpi', 'dashboard', 'healthcare', 'excel'],
    images: ['/images/products/hospital-dashboard.svg'],
    thumbnail: '/images/products/hospital-dashboard.svg',
    downloadableFiles: ['hospital-kpi-dashboard.xlsx'],
    version: '2.3',
    changelog: 'Added bed occupancy forecasting, improved mobile view',
    demoUrl: '#',
    faq: [
      { question: 'Which Excel version is required?', answer: 'Works with Excel 2016 and above, including Microsoft 365.' },
      { question: 'Can I customize the metrics?', answer: 'Yes, the dashboard is fully customizable with documented instructions.' },
    ],
    relatedProducts: ['prod2', 'prod3'],
    seoTitle: 'Hospital KPI Dashboard Pro - TrueWorks',
    seoDescription: 'Professional hospital KPI dashboard for Excel. Track 45+ healthcare metrics.',
    downloadLimit: 5,
    downloadExpiry: 365,
    status: 'active',
    featured: true,
    salesCount: 12,
    createdAt: '2025-01-15',
    updatedAt: '2025-06-20',
  },
  {
    _id: 'prod2',
    name: 'Financial Model & Valuation Toolkit',
    sku: 'TW-FM-002',
    slug: 'financial-model-valuation-toolkit',
    shortDescription: 'Investment-grade financial modeling toolkit with DCF, LBO, M&A models, and automated sensitivity analysis.',
    description: 'Professional financial modeling suite used by finance teams across East Africa. Includes discounted cash flow (DCF) analysis, leveraged buyout (LBO) models, merger & acquisition (M&A) frameworks, and automated sensitivity analysis with data tables and scenario manager.',
    price: 250000,
    category: 'Financial Models',
    industry: 'Finance',
    fileType: 'Excel (.xlsx)',
    tags: ['financial', 'valuation', 'dcf', 'lbo', 'modeling'],
    images: ['/images/products/financial-model.svg'],
    thumbnail: '/images/products/financial-model.svg',
    downloadableFiles: ['financial-model-toolkit.xlsx'],
    version: '3.1',
    changelog: 'Added new scenario analysis module',
    faq: [
      { question: 'Is this suitable for investment banking?', answer: 'Yes, built to investment banking standards.' },
    ],
    relatedProducts: ['prod1', 'prod3'],
    seoTitle: 'Financial Model & Valuation Toolkit - TrueWorks',
    seoDescription: 'Investment-grade financial modeling toolkit with DCF, LBO, M&A models.',
    downloadLimit: 3,
    downloadExpiry: 365,
    status: 'active',
    featured: true,
    salesCount: 8,
    createdAt: '2025-02-01',
    updatedAt: '2025-06-15',
  },
  {
    _id: 'prod3',
    name: 'NGO Grant Management System',
    sku: 'TW-NGO-003',
    slug: 'ngo-grant-management-system',
    shortDescription: 'End-to-end grant management system for NGOs with donor tracking, budget vs actual, and compliance reporting.',
    description: 'Complete grant management solution for non-profit organizations. Track multiple grants, manage donor relationships, monitor budget utilization, generate compliance reports, and automate financial tracking for USAID, UN, EU, and local funders.',
    price: 180000,
    salePrice: 129000,
    category: 'Financial Models',
    industry: 'NGO',
    fileType: 'Excel (.xlsx)',
    tags: ['ngo', 'grant', 'donor', 'non-profit', 'compliance'],
    images: ['/images/products/ngo-grant-system.svg'],
    thumbnail: '/images/products/ngo-grant-system.svg',
    downloadableFiles: ['ngo-grant-system.xlsx'],
    version: '1.5',
    changelog: 'Added donor contribution analysis',
    faq: [
      { question: 'How many grants can I manage?', answer: 'Unlimited grants with the current structure.' },
    ],
    relatedProducts: ['prod1', 'prod4'],
    seoTitle: 'NGO Grant Management System - TrueWorks',
    seoDescription: 'Professional grant management system for NGOs with donor tracking.',
    downloadLimit: 5,
    downloadExpiry: 365,
    status: 'active',
    featured: true,
    salesCount: 6,
    createdAt: '2025-03-10',
    updatedAt: '2025-06-25',
  },
  {
    _id: 'prod4',
    name: 'School Administration Dashboard',
    sku: 'TW-SCH-004',
    slug: 'school-administration-dashboard',
    shortDescription: 'Complete school management dashboard with student tracking, fee collection, and staff management.',
    description: 'Comprehensive school administration system for primary and secondary schools. Manage student enrollment, track fee payments, monitor staff performance, generate report cards, and maintain academic records.',
    price: 120000,
    category: 'Dashboards',
    industry: 'Schools',
    fileType: 'Excel (.xlsx)',
    tags: ['school', 'education', 'students', 'fees', 'administration'],
    images: ['/images/products/budget-template.svg'],
    thumbnail: '/images/products/budget-template.svg',
    downloadableFiles: ['school-admin-dashboard.xlsx'],
    version: '2.0',
    changelog: 'Added termly reporting module',
    faq: [],
    relatedProducts: ['prod1', 'prod5'],
    seoTitle: 'School Administration Dashboard - TrueWorks',
    seoDescription: 'Complete school management dashboard with student tracking and fee collection.',
    downloadLimit: 5,
    downloadExpiry: 365,
    status: 'active',
    featured: false,
    salesCount: 4,
    createdAt: '2025-04-01',
    updatedAt: '2025-06-10',
  },
  {
    _id: 'prod5',
    name: 'Church Stewardship & Finance System',
    sku: 'TW-CH-005',
    slug: 'church-stewardship-finance-system',
    shortDescription: 'Church financial management system with tithe tracking, expense management, and annual budgeting.',
    description: 'Designed for churches in Uganda and East Africa. Track tithes and offerings, manage expenses by ministry, generate financial reports for church boards, and create annual budgets.',
    price: 85000,
    category: 'Budget Templates',
    industry: 'Churches',
    fileType: 'Excel (.xlsx)',
    tags: ['church', 'stewardship', 'finance', 'tithe', 'offering'],
    images: ['/images/products/budget-template.svg'],
    thumbnail: '/images/products/budget-template.svg',
    downloadableFiles: ['church-finance-system.xlsx'],
    version: '1.2',
    changelog: 'Added multi-currency support',
    faq: [],
    relatedProducts: ['prod3', 'prod4'],
    seoTitle: 'Church Stewardship & Finance System - TrueWorks',
    seoDescription: 'Church financial management system with tithe tracking and budgeting.',
    downloadLimit: 5,
    downloadExpiry: 365,
    status: 'active',
    featured: false,
    salesCount: 3,
    createdAt: '2025-04-15',
    updatedAt: '2025-06-05',
  },
  {
    _id: 'prod6',
    name: 'HR & Payroll Management System',
    sku: 'TW-HR-006',
    slug: 'hr-payroll-management-system',
    shortDescription: 'Complete HR and payroll system with employee records, payroll processing, and leave management.',
    description: 'Professional HR management system for growing organizations. Manage employee records, process payroll with URA tax calculations, track leave balances, and generate HR reports.',
    price: 200000,
    salePrice: 149000,
    category: 'HR Systems',
    industry: 'HR',
    fileType: 'Excel (.xlsx)',
    tags: ['hr', 'payroll', 'employees', 'leave', 'tax'],
    images: ['/images/products/hr-system.svg'],
    thumbnail: '/images/products/hr-system.svg',
    downloadableFiles: ['hr-payroll-system.xlsx'],
    version: '2.1',
    changelog: 'Updated URA tax tables for 2025',
    faq: [
      { question: 'Does it handle PAYE calculations?', answer: 'Yes, with current URA tax rates and bands.' },
    ],
    relatedProducts: ['prod2', 'prod1'],
    seoTitle: 'HR & Payroll Management System - TrueWorks',
    seoDescription: 'Complete HR and payroll system with URA tax calculations.',
    downloadLimit: 3,
    downloadExpiry: 365,
    status: 'active',
    featured: true,
    salesCount: 7,
    createdAt: '2025-01-20',
    updatedAt: '2025-06-28',
  },
  {
    _id: 'prod7',
    name: 'SME Business Budget & Forecast Pro',
    sku: 'TW-BF-007',
    slug: 'sme-business-budget-forecast-pro',
    shortDescription: 'Professional budgeting and forecasting toolkit for SMEs with 3-statement model integration.',
    description: 'Purpose-built for small and medium enterprises in Uganda. Create professional budgets, forecast revenue and expenses, manage cash flow, and integrate with a complete 3-statement financial model.',
    price: 95000,
    category: 'Budget Templates',
    industry: 'Business',
    fileType: 'Excel (.xlsx)',
    tags: ['sme', 'budget', 'forecast', 'cash-flow', 'business'],
    images: ['/images/products/budget-template.svg'],
    thumbnail: '/images/products/budget-template.svg',
    downloadableFiles: ['sme-budget-forecast.xlsx'],
    version: '1.8',
    changelog: 'Added cash flow forecasting module',
    faq: [],
    relatedProducts: ['prod2', 'prod6'],
    seoTitle: 'SME Business Budget & Forecast Pro - TrueWorks',
    seoDescription: 'Professional budgeting and forecasting toolkit for SMEs.',
    downloadLimit: 5,
    downloadExpiry: 365,
    status: 'active',
    featured: false,
    salesCount: 5,
    createdAt: '2025-02-15',
    updatedAt: '2025-05-30',
  },
  {
    _id: 'prod8',
    name: 'Agriculture Farm Management System',
    sku: 'TW-AG-008',
    slug: 'agriculture-farm-management-system',
    shortDescription: 'Farm management system with crop tracking, livestock records, and harvest forecasting.',
    description: 'Comprehensive farm management solution for agribusinesses. Track crop cycles, manage livestock inventories, forecast harvest yields, and analyze farm profitability.',
    price: 110000,
    category: 'Inventory Systems',
    industry: 'Agriculture',
    fileType: 'Excel (.xlsx)',
    tags: ['agriculture', 'farm', 'crops', 'livestock', 'harvest'],
    images: ['/images/products/budget-template.svg'],
    thumbnail: '/images/products/budget-template.svg',
    downloadableFiles: ['farm-management-system.xlsx'],
    version: '1.0',
    changelog: 'Initial release',
    faq: [],
    relatedProducts: ['prod7', 'prod3'],
    seoTitle: 'Agriculture Farm Management System - TrueWorks',
    seoDescription: 'Farm management system with crop tracking and harvest forecasting.',
    downloadLimit: 5,
    downloadExpiry: 365,
    status: 'active',
    featured: false,
    salesCount: 2,
    createdAt: '2025-05-01',
    updatedAt: '2025-06-01',
  },
  {
    _id: 'prod9',
    name: 'Ultimate Business Bundle',
    sku: 'TW-BND-009',
    slug: 'ultimate-business-bundle',
    shortDescription: 'Complete business toolkit: financial model, budget, HR system, and dashboard at 40% discount.',
    description: 'The ultimate business package. Includes the Financial Model & Valuation Toolkit, SME Budget & Forecast Pro, HR & Payroll System, and Executive Dashboard. Save 40% compared to buying individually.',
    price: 550000,
    salePrice: 329000,
    category: 'Bundles',
    industry: 'Business',
    fileType: 'Excel (.xlsx)',
    tags: ['bundle', 'business', 'complete', 'discount'],
    images: ['/images/products/financial-model.svg'],
    thumbnail: '/images/products/financial-model.svg',
    downloadableFiles: ['business-bundle.zip'],
    version: '2.0',
    changelog: 'Updated all included templates',
    faq: [
      { question: 'What is included in the bundle?', answer: '4 premium templates valued at $150+.' },
    ],
    relatedProducts: ['prod2', 'prod6', 'prod7'],
    seoTitle: 'Ultimate Business Bundle - TrueWorks',
    seoDescription: 'Complete business toolkit bundle at 40% discount.',
    downloadLimit: 10,
    downloadExpiry: 365,
    status: 'active',
    featured: true,
    salesCount: 3,
    createdAt: '2025-03-01',
    updatedAt: '2025-06-20',
  },
];

export const testimonials = [
  {
    id: 't1',
    name: 'Dr. Sarah Nambozo',
    role: 'Hospital Administrator',
    company: 'Kampala Medical Centre',
    quote: 'The Hospital KPI Dashboard transformed how we track our performance. We reduced reporting time by 80% and gained real-time visibility into our operations.',
    rating: 5,
    image: '/images/testimonials/sarah.jpg',
  },
  {
    id: 't2',
    name: 'James Ochieng',
    role: 'Finance Director',
    company: 'East African Development Fund',
    quote: 'TrueWorks financial models are investment-grade. We use them for all our portfolio company valuations. Outstanding quality and attention to detail.',
    rating: 5,
    image: '/images/testimonials/james.jpg',
  },
  {
    id: 't3',
    name: 'Grace Akello',
    role: 'Program Manager',
    company: 'Hope Relief NGO',
    quote: 'The NGO Grant Management System made donor reporting effortless. Our compliance audits have never been smoother. Highly recommended for any non-profit.',
    rating: 5,
    image: '/images/testimonials/grace.jpg',
  },
  {
    id: 't4',
    name: 'Peter Mukasa',
    role: 'Head of HR',
    company: 'Royal Suite Hotels',
    quote: 'We moved from manual spreadsheets to TrueWorks HR system. Payroll processing that used to take 3 days now takes 2 hours. Exceptional product.',
    rating: 5,
    image: '/images/testimonials/peter.jpg',
  },
  {
    id: 't5',
    name: 'Rebecca Tumusiime',
    role: 'School Principal',
    company: 'Green Acres Academy',
    quote: 'Managing school finances used to be a nightmare. The School Dashboard gave us clarity and control. Every school in Uganda needs this.',
    rating: 4,
    image: '/images/testimonials/rebecca.jpg',
  },
];

export const blogPosts: BlogPost[] = [
  {
    _id: 'b1',
    title: '5 KPIs Every Ugandan Hospital Should Track in 2025',
    slug: '5-kpis-every-ugandan-hospital-should-track',
    excerpt: 'Discover the key performance indicators that drive better patient outcomes and financial sustainability for healthcare facilities in Uganda.',
    content: '',
    category: 'Healthcare',
    tags: ['kpi', 'healthcare', 'hospital'],
    image: '/images/blog/healthcare-kpis.jpg',
    author: 'TrueWorks Team',
    readingTime: 8,
    featured: true,
    publishedAt: '2025-06-15',
    createdAt: '2025-06-10',
  },
  {
    _id: 'b2',
    title: 'Building a Budget That Drives Growth: A Guide for SMEs',
    slug: 'building-budget-that-drives-growth',
    excerpt: 'Learn how small and medium enterprises in East Africa can create budgets that align with strategic goals and drive sustainable growth.',
    content: '',
    category: 'Finance',
    tags: ['budget', 'sme', 'growth'],
    image: '/images/blog/budget-guide.jpg',
    author: 'TrueWorks Team',
    readingTime: 12,
    featured: true,
    publishedAt: '2025-05-20',
    createdAt: '2025-05-15',
  },
  {
    _id: 'b3',
    title: 'Financial Modeling Best Practices for East African Businesses',
    slug: 'financial-modeling-best-practices',
    excerpt: 'A comprehensive guide to building robust financial models that stand up to investor scrutiny and drive better business decisions.',
    content: '',
    category: 'Finance',
    tags: ['financial modeling', 'valuation', 'best practices'],
    image: '/images/blog/financial-modeling.jpg',
    author: 'TrueWorks Team',
    readingTime: 15,
    featured: false,
    publishedAt: '2025-04-10',
    createdAt: '2025-04-05',
  },
];

export const resources: Resource[] = [
  {
    _id: 'r1',
    title: 'Hospital KPI Dashboard Guide',
    type: 'guide',
    description: 'A comprehensive guide to implementing and customizing your hospital KPI dashboard.',
    image: '/images/resources/kpi-guide.jpg',
    url: '#',
    featured: true,
    category: 'Healthcare',
    createdAt: '2025-06-01',
  },
  {
    _id: 'r2',
    title: 'NGO Financial Compliance in Uganda',
    type: 'case_study',
    description: 'How organizations maintain compliance with NGO board requirements using our systems.',
    image: '/images/resources/ngo-compliance.jpg',
    url: '#',
    featured: true,
    category: 'NGO',
    createdAt: '2025-05-15',
  },
  {
    _id: 'r3',
    title: 'Excel Shortcuts Productivity Cheat Sheet',
    type: 'template',
    description: 'Free downloadable cheat sheet with 50+ Excel shortcuts to boost your productivity.',
    image: '/images/resources/excel-cheatsheet.jpg',
    url: '#',
    featured: false,
    category: 'Productivity',
    createdAt: '2025-04-20',
  },
];

export const orders: Order[] = [
  {
    _id: 'ord1',
    orderNumber: 'TW-2025-0001',
    customerId: 'c1',
    customer: { name: 'Dr. Sarah Nambozo', email: 'sarah@kmc.ug', phone: '+256 700 123456' },
    items: [{ productId: 'prod1', productName: 'Hospital KPI Dashboard Pro', quantity: 1, price: 99000 }],
    subtotal: 99000,
    total: 99000,
    paymentMethod: 'mtn_momo',
    paymentStatus: 'completed',
    orderStatus: 'completed',
    downloadLinks: [{
      productId: 'prod1',
      productName: 'Hospital KPI Dashboard Pro',
      url: '#',
      downloadCount: 2,
      remainingDownloads: 3,
      expiryDate: '2026-06-20',
      status: 'active',
    }],
    createdAt: '2025-06-20',
    updatedAt: '2025-06-20',
  },
  {
    _id: 'ord2',
    orderNumber: 'TW-2025-0002',
    customerId: 'c2',
    customer: { name: 'James Ochieng', email: 'james@eadf.org' },
    items: [{ productId: 'prod2', productName: 'Financial Model & Valuation Toolkit', quantity: 1, price: 250000 }],
    subtotal: 250000,
    total: 250000,
    paymentMethod: 'visa',
    paymentStatus: 'completed',
    orderStatus: 'completed',
    downloadLinks: [{
      productId: 'prod2',
      productName: 'Financial Model & Valuation Toolkit',
      url: '#',
      downloadCount: 1,
      remainingDownloads: 2,
      expiryDate: '2026-06-15',
      status: 'active',
    }],
    createdAt: '2025-06-15',
    updatedAt: '2025-06-15',
  },
  {
    _id: 'ord3',
    orderNumber: 'TW-2025-0003',
    customerId: 'c3',
    customer: { name: 'Grace Akello', email: 'grace@hoperelief.org' },
    items: [{ productId: 'prod3', productName: 'NGO Grant Management System', quantity: 1, price: 129000 }],
    subtotal: 129000,
    total: 129000,
    paymentMethod: 'airtel_money',
    paymentStatus: 'completed',
    orderStatus: 'completed',
    downloadLinks: [{
      productId: 'prod3',
      productName: 'NGO Grant Management System',
      url: '#',
      downloadCount: 0,
      remainingDownloads: 5,
      expiryDate: '2026-06-25',
      status: 'active',
    }],
    createdAt: '2025-06-25',
    updatedAt: '2025-06-25',
  },
  {
    _id: 'ord4',
    orderNumber: 'TW-2025-0004',
    customerId: 'c4',
    customer: { name: 'Peter Mukasa', email: 'peter@royalsuites.ug' },
    items: [{ productId: 'prod6', productName: 'HR & Payroll Management System', quantity: 1, price: 149000 }],
    subtotal: 149000,
    total: 149000,
    paymentMethod: 'mtn_momo',
    paymentStatus: 'pending',
    orderStatus: 'processing',
    downloadLinks: [],
    createdAt: '2025-06-28',
    updatedAt: '2025-06-28',
  },
];

export const customers: Customer[] = [
  { _id: 'c1', name: 'Dr. Sarah Nambozo', email: 'sarah@kmc.ug', phone: '+256 700 123456', company: 'Kampala Medical Centre', industry: 'Healthcare', newsletter: true, favoriteCategories: ['Dashboards'], lifetimeValue: 99000, totalOrders: 1, totalDownloads: 2, createdAt: '2025-06-20', lastPurchaseAt: '2025-06-20' },
  { _id: 'c2', name: 'James Ochieng', email: 'james@eadf.org', company: 'East African Development Fund', industry: 'Finance', newsletter: true, favoriteCategories: ['Financial Models'], lifetimeValue: 250000, totalOrders: 1, totalDownloads: 1, createdAt: '2025-06-15', lastPurchaseAt: '2025-06-15' },
  { _id: 'c3', name: 'Grace Akello', email: 'grace@hoperelief.org', company: 'Hope Relief NGO', industry: 'NGO', newsletter: true, favoriteCategories: ['Financial Models'], lifetimeValue: 129000, totalOrders: 1, totalDownloads: 0, createdAt: '2025-06-25', lastPurchaseAt: '2025-06-25' },
  { _id: 'c4', name: 'Peter Mukasa', email: 'peter@royalsuites.ug', company: 'Royal Suite Hotels', industry: 'HR', newsletter: false, favoriteCategories: ['HR Systems'], lifetimeValue: 149000, totalOrders: 1, totalDownloads: 0, createdAt: '2025-06-28' },
  { _id: 'c5', name: 'Rebecca Tumusiime', email: 'rebecca@greenacres.ug', company: 'Green Acres Academy', industry: 'Schools', newsletter: true, favoriteCategories: ['Dashboards'], lifetimeValue: 120000, totalOrders: 1, totalDownloads: 3, createdAt: '2025-05-10', lastPurchaseAt: '2025-05-10' },
];

export const reviews: Review[] = [
  { _id: 'rev1', productId: 'prod1', customerId: 'c1', customerName: 'Dr. Sarah Nambozo', rating: 5, title: 'Game changer for our hospital', content: 'This dashboard gave us visibility we never had before. Highly recommended.', featured: true, approved: true, createdAt: '2025-06-25' },
  { _id: 'rev2', productId: 'prod2', customerId: 'c2', customerName: 'James Ochieng', rating: 5, title: 'Investment-grade models', content: 'Used for multiple portfolio valuations. Exceptional quality.', featured: true, approved: true, createdAt: '2025-06-20' },
  { _id: 'rev3', productId: 'prod3', customerId: 'c3', customerName: 'Grace Akello', rating: 5, title: 'Donor reporting made easy', content: 'Our compliance reporting improved dramatically.', featured: false, approved: true, createdAt: '2025-06-28' },
];

export const analytics: AnalyticsData = {
  totalRevenue: 738000,
  revenueToday: 129000,
  revenueThisMonth: 548000,
  totalOrders: 4,
  pendingOrders: 1,
  successfulPayments: 3,
  productsSold: 4,
  activeProducts: 9,
  totalDownloads: 6,
  activeCustomers: 5,
  newsletterSubscribers: 128,
  conversionRate: 3.2,
  averageOrderValue: 156750,
  storePerformanceScore: 87,
};

export const salesTrends: SalesTrend[] = [
  { date: '2025-01', revenue: 150000, orders: 1 },
  { date: '2025-02', revenue: 250000, orders: 1 },
  { date: '2025-03', revenue: 180000, orders: 1 },
  { date: '2025-04', revenue: 120000, orders: 1 },
  { date: '2025-05', revenue: 110000, orders: 1 },
  { date: '2025-06', revenue: 548000, orders: 3 },
];

export const monthlyRevenue = [
  { month: 'Jan', revenue: 0 },
  { month: 'Feb', revenue: 150000 },
  { month: 'Mar', revenue: 250000 },
  { month: 'Apr', revenue: 180000 },
  { month: 'May', revenue: 120000 },
  { month: 'Jun', revenue: 348000 },
];

export const paymentMethods = [
  { name: 'MTN MoMo', percentage: 50, amount: 248000 },
  { name: 'Airtel Money', percentage: 25, amount: 129000 },
  { name: 'Visa', percentage: 25, amount: 250000 },
];

export const downloadStats = [
  { product: 'Hospital KPI Dashboard', downloads: 2 },
  { product: 'Financial Model Toolkit', downloads: 1 },
  { product: 'School Dashboard', downloads: 3 },
];
